# Generated by Django 2.1.7 on 2019-12-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funny_Videos', '0002_auto_20191219_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videos',
            new_name='video',
        ),
    ]
