# Generated by Django 2.1.7 on 2020-01-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funny_pictures', '0004_auto_20200108_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.FileField(upload_to='funny_pictures/static/images/'),
        ),
    ]
