# Generated by Django 2.1.7 on 2020-01-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funny_pictures', '0005_auto_20200108_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.FileField(upload_to='funny_pictures/static/funny_pictures/images/'),
        ),
    ]
