# Generated by Django 2.1.7 on 2020-02-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funny_pictures', '0013_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
